# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "typeAHippie"
description: > # this means to ignore newlines until "email:"
   Tales of tech from the inside and outside

email: typeatechhippie@gmail.com
#blog logo
logo: "/assets/images/peaceSign.png"
# blog cover
cover: "/assets/images/sandals.jpg"

name: 'Annie Kramer'
author: 'Annie Kramer'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/goingglacial
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/goingglacial
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
